# Generated by Django 4.1.7 on 2023-06-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBoxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('total_request', models.IntegerField(default=0)),
                ('emailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailbox.emailboxmodel')),
            ],
        ),
    ]
